import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/header";
import ReduxProvider from "@/redux/provider";
import { Toaster } from "sonner";
import { Client, HydrationProvider } from "react-hydration-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HydrationProvider>
          <Client>
            <ReduxProvider>
              <Toaster position="top-right" richColors />
              <Header />
              {children}
            </ReduxProvider>
          </Client>
        </HydrationProvider>
      </body>
    </html>
  );
}
